name: Build Status

on:
  push:
    branches:
      - master
      - '4.next'
  pull_request:
    branches:
      - '*'

jobs:
  # testsuite:
  #   runs-on: ubuntu-18.04
  #   defaults:
  #     run:
  #       working-directory: ./php
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       php-version: ['7.4', '8.0']
  #       db-type: [mysql, mariadb]
  #   name: PHP ${{ matrix.php-version }}

  #   steps:
  #   - name: Setup MySQL latest
  #     if: matrix.db-type == 'mysql'
  #     run: docker run --rm --name=mysqld -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=cakephp -p 3306:3306 -d mysql --default-authentication-plugin=mysql_native_password --disable-log-bin

  #   - uses: getong/mariadb-action@v1.1
  #     if: matrix.db-type == 'mariadb'
  #     with:
  #       mysql database: 'cakephp'
  #       mysql root password: 'root'

  #   - uses: actions/checkout@v2

  #   - name: Setup PHP
  #     uses: shivammathur/setup-php@v2
  #     with:
  #       php-version: ${{ matrix.php-version }}
  #       extensions: mbstring, intl, pdo_sqlite, pdo_mysql
  #       coverage: none

  #   - name: composer install
  #     run: |
  #       if [[ ${{ matrix.db-type }} == 'mysql' ]]; then export DB_URL='mysql://root:root@127.0.0.1/cakephp'; fi
  #       if [[ ${{ matrix.db-type }} == 'mariadb' ]]; then export DB_URL='mysql://root:root@127.0.0.1/cakephp'; fi
  #       if [[ ${{ matrix.php-version }} == '8.0' ]]; then
  #         composer install --ignore-platform-reqs
  #       else
  #         composer install
  #       fi
  #       composer run-script post-install-cmd --no-interaction

  #   - name: Run PHPUnit
  #     run: |
  #         vendor/bin/phpunit

  coding-standard:
    name: Coding Standard
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: ./src

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extensions: mbstring, intl
        coverage: none

    - name: composer install
      run: composer install

    - name: Run PHP CodeSniffer
      run: composer cs-check

  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: ./src

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extensions: mbstring, intl
        coverage: none

    - name: composer install
      run: composer require --dev phpstan/phpstan:^0.12

    - name: Run phpstan
      run: vendor/bin/phpstan.phar analyse
